export default {
    allTags: [
        "Beginner",
        "Intermediate",
        "Expert",
        "DeFi",
        "Gaming",
        "Governance",
        "Mobile",
        "Security",
        "Serum",
        "Arweave",
        "Web3.js",
        "React.js",
        "Svelte",
        "Vue.js",
        "Rust",
        "JavaScript",
        "C#",
        "Golang",
        "Python",
        "Java",
        "Swift",
        "CLI",
        "Kotlin",
    ]
};
